// 📄 ViXoRa Resume Data — ۵۰ قالب دقیق (۲۰ کشور + ۱۵ بین‌المللی + ۱۵ ایرانی)
// src/pages/tools/resume/resume-data.js
// photo: required | optional | forbidden — بر اساس عرف واقعی هر مقصد

export const SECTION_DEFS = {
  summary: { en: 'Professional Summary', fa: 'خلاصه حرفه‌ای' },
  objective: { en: 'Career Objective', fa: 'هدف شغلی' },
  skills: { en: 'Skills', fa: 'مهارت‌ها' },
  exp: { en: 'Work Experience', fa: 'سوابق کاری' },
  edu: { en: 'Education', fa: 'تحصیلات' },
  langs: { en: 'Languages', fa: 'زبان‌ها' },
  certs: { en: 'Certifications', fa: 'گواهینامه‌ها' },
  projects: { en: 'Projects', fa: 'پروژه‌ها' },
  refs: { en: 'References', fa: 'معرف‌ها' },
  personal: { en: 'Personal Details', fa: 'مشخصات فردی' },
  hobbies: { en: 'Interests', fa: 'علایق' },
  decl: { en: 'Declaration', fa: 'تعهدنامه' },
};

export const PERSONAL_DEFS = {
  dob: { en: 'Date of Birth', fa: 'تاریخ تولد' },
  pob: { en: 'Place of Birth', fa: 'محل تولد' },
  nat: { en: 'Nationality', fa: 'ملیت' },
  marital: { en: 'Marital Status', fa: 'وضعیت تأهل' },
  gender: { en: 'Gender', fa: 'جنسیت' },
  address: { en: 'Address', fa: 'نشانی' },
  visa: { en: 'Visa / Work Rights', fa: 'وضعیت ویزا/اقامت' },
  military: { en: 'Military Service', fa: 'وضعیت نظام‌وظیفه' },
  children: { en: 'Children', fa: 'فرزندان' },
};

export const THEMES = {
  navy: { c1: '#1e3a8a', c2: '#3b82f6', name: 'سرمه‌ای' },
  teal: { c1: '#0f766e', c2: '#14b8a6', name: 'سبز کله‌غازی' },
  wine: { c1: '#881337', c2: '#e11d48', name: 'شرابی' },
  charcoal: { c1: '#1f2937', c2: '#6b7280', name: 'ذغالی' },
  royal: { c1: '#6d28d9', c2: '#a855f7', name: 'بنفش سلطنتی' },
  forest: { c1: '#14532d', c2: '#22c55e', name: 'سبز جنگلی' },
  copper: { c1: '#9a3412', c2: '#f97316', name: 'مسی' },
  slate: { c1: '#334155', c2: '#0ea5e9', name: 'سنگ‌آبی' },
  crimson: { c1: '#991b1b', c2: '#ef4444', name: 'زرشکی' },
  ocean: { c1: '#0c4a6e', c2: '#06b6d4', name: 'اقیانوسی' },
  gold: { c1: '#713f12', c2: '#eab308', name: 'طلایی' },
  mono: { c1: '#111111', c2: '#555555', name: 'تک‌رنگ ATS' },
};

export const FONTS = {
  modern: { name: 'مدرن (سن‌سریف)', en: 'Inter, Arial, sans-serif', fa: 'Vazirmatn, Tahoma, sans-serif' },
  serif: { name: 'رسمی (سریف)', en: 'Georgia, "Times New Roman", serif', fa: '"Noto Naskh Arabic", Tahoma, serif' },
  round: { name: 'دوستانه (گرد)', en: 'Verdana, Geneva, sans-serif', fa: 'Samim, Tahoma, sans-serif' },
  sharp: { name: 'تیز (باریک)', en: '"Arial Narrow", Arial, sans-serif', fa: 'Tahoma, sans-serif' },
};

export const LAYOUTS = {
  minimal: { name: 'مینیمال ATS', desc: 'تک‌ستون، بدون گرافیک — عبور از فیلتر ربات‌ها' },
  classic: { name: 'کلاسیک', desc: 'تک‌ستون با خط جداکننده — استاندارد جهانی' },
  sidebar: { name: 'دو‌ستونه (سایدبار)', desc: 'مشخصات و مهارت در ستون کناری' },
  band: { name: 'هدر نواری', desc: 'هدر رنگی پهن با نام درشت' },
  tabular: { name: 'جدولی (Lebenslauf)', desc: 'دو‌ستون تاریخ/شرح — استاندارد آلمانی' },
  card: { name: 'کارتی با عکس', desc: 'هدر کارتی با عکس پرسنلی' },
  timeline: { name: 'خط زمانی', desc: 'سوابق روی خط زمان — مناسب خلاق‌ها' },
  academic: { name: 'آکادمیک', desc: 'چندبخش مفصل — تحصیلی و پژوهشی' },
};

/* ============ ۲۰ کشور (عرف واقعی سفارت/کارفرما) ============ */
export const TEMPLATES = [
// --- آمریکا ---
{ id: 'ct-usa', group: 'country', icon: '🇺🇸', name: 'United States', fa: 'آمریکا — رزومه سفارت/کارفرما', layout: 'minimal', theme: 'mono', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه (باتجربه‌ها حداکثر ۲)',
  sections: ['summary', 'skills', 'exp', 'edu', 'projects', 'certs'], personal: [],
  blurb: 'رزومه آمریکایی: ۱ صفحه، بدون عکس و بدون هیچ اطلاعات شخصی. فقط دستاوردهای عددی.',
  tips: ['عکس، سن، تأهل و ملیت هرگز! گذاشتنشان یعنی رد خودکار در ATS.', 'هر بولت با فعل قوی + عدد: «فروش را ۳۴٪ رشد دادم».', 'کاغذ Letter است؛ حاشیه‌ها را دست نزن تا در چاپ آمریکا به‌هم نریزد.'] },
{ id: 'ct-canada', group: 'country', icon: '🇨🇦', name: 'Canada', fa: 'کانادا — رزومه اکسپرس‌انتری/کارفرما', layout: 'classic', theme: 'slate', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'certs', 'langs'], personal: [],
  blurb: 'رزومه کانادایی: تمیز، بدون عکس، با تأکید بر مهارت‌های قابل‌انتقال و دوزبانگی.',
  tips: ['اگر فرانسه بلدی حتماً بنویس — برای دولت فدرال امتیاز دارد.', 'شماره SIN و عکس ممنوع؛ فقط شهر و استان کافی است.', 'بخش «Highlights» اول رزومه را با ۴-۵ بولت قوی پر کن.'] },
{ id: 'ct-germany', group: 'country', icon: '🇩🇪', name: 'Deutschland', fa: 'آلمان — Lebenslauf tabular', layout: 'tabular', theme: 'navy', font: 'modern', lang: 'en', photo: 'required', pageMax: 2, pages: '۲ صفحه (جدولی)',
  sections: ['personal', 'exp', 'edu', 'skills', 'langs', 'certs', 'hobbies', 'decl'], personal: ['dob', 'pob', 'nat', 'marital', 'address'],
  blurb: 'لبنزلاف آلمانی: جدول زمانی دقیق، عکس پرسنلی، امضا و تاریخ پایین صفحه.',
  tips: ['عکس رسمی پاسپورتی بالا-راست؛ لبخند ملایم و پس‌زمینه خنثی.', 'سوابق را از قدیم به جدید بنویس (برعکس آمریکا) و هیچ گپ زمانی بدون توضیح نگذار.', 'پایین صفحه مکان + تاریخ + امضا بگذار؛ برای بلوکارت مدارک ضمیمه جدا فرستاده می‌شود.'] },
{ id: 'ct-uk', group: 'country', icon: '🇬🇧', name: 'United Kingdom', fa: 'بریتانیا — CV دوساله', layout: 'classic', theme: 'navy', font: 'serif', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۲ صفحه (CV)',
  sections: ['summary', 'exp', 'edu', 'skills', 'certs', 'refs'], personal: [],
  blurb: 'سی‌وی بریتانیایی: ۲ صفحه، بدون عکس، با Personal Statement قوی در شروع.',
  tips: ['اینجا به آن CV می‌گویند نه Resume — ولی همان ۲ صفحه است.', 'سن، عکس و ملیت ننویس؛ ولی «References available on request» تهش بگذار.', 'املای بریتیش (organised نه organized) را رعایت کن.'] },
{ id: 'ct-australia', group: 'country', icon: '🇦🇺', name: 'Australia', fa: 'استرالیا — CV با رفرنس', layout: 'classic', theme: 'ocean', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 3, pages: '۲ تا ۳ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'certs', 'refs'], personal: ['visa'],
  blurb: 'رزومه استرالیایی: مفصل‌تر از آمریکا، بدون عکس، با معرف‌های واقعی و وضعیت ویزا.',
  tips: ['وضعیت حق کار (Visa status) را حتماً بنویس — برای غیرشهروندها حیاتی است.', 'بولت‌ها را STAR بنویس: موقعیت، وظیفه، اقدام، نتیجه.', '۲ معرف با تلفن واقعی ته رزومه بگذار؛ استرالیایی‌ها زنگ می‌زنند!'] },
{ id: 'ct-france', group: 'country', icon: '🇫🇷', name: 'France', fa: 'فرانسه — CV یک‌صفحه‌ای', layout: 'card', theme: 'wine', font: 'serif', lang: 'en', photo: 'optional', pageMax: 1, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs', 'hobbies'], personal: ['dob', 'nat', 'address'],
  blurb: 'سی‌وی فرانسوی: رسمی و موجز، عکس رایج، علایق جدی گرفته می‌شود.',
  tips: ['از اغراق آمریکایی («passionate ninja») پرهیز کن؛ لحن رسمی و فروتن.', 'مدرک زبان فرانسه (DELF/DALF) را با سطح دقیق بنویس.', 'بخش علایق را حذف نکن — فرانسوی‌ها شخصیت را هم می‌سنجند.'] },
{ id: 'ct-netherlands', group: 'country', icon: '🇳🇱', name: 'Netherlands', fa: 'هلند — CV رک و مستقیم', layout: 'minimal', theme: 'copper', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'langs', 'certs'], personal: ['dob', 'nat'],
  blurb: 'رزومه هلندی: مستقیم و بدون حاشیه، مهارت‌محور، عکس اختیاری.',
  tips: ['هلندی‌ها رک‌اند: دستاورد را شفاف و بدون اغراق بنویس.', 'سطح انگلیسی (و هلندی اگر بلدی) را دقیق مشخص کن.', 'برای ویزای highly skilled، تطابق عنوان شغلی با لیست IND مهم است.'] },
{ id: 'ct-sweden', group: 'country', icon: '🇸🇪', name: 'Sweden', fa: 'سوئد — CV تیم‌محور', layout: 'minimal', theme: 'ocean', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs'], personal: [],
  blurb: 'رزومه سوئدی: فروتن، تیم‌محور، با تأکید بر همکاری و ارزش‌های اجتماعی.',
  tips: ['به‌جای «من بهترینم» بنویس «در تیم X به نتیجه Y رسیدیم».', 'cover letter جدا (personligt brev) در سوئد خیلی مهم است.', 'عکس اختیاری است؛ بدون عکس هم کاملاً پذیرفته است.'] },
{ id: 'ct-swiss', group: 'country', icon: '🇨🇭', name: 'Switzerland', fa: 'سوئیس — CV دقیق و مفصل', layout: 'tabular', theme: 'crimson', font: 'serif', lang: 'en', photo: 'required', pageMax: 2, pages: '۲ صفحه',
  sections: ['personal', 'exp', 'edu', 'skills', 'langs', 'certs', 'refs'], personal: ['dob', 'nat', 'marital', 'address'],
  blurb: 'رزومه سوئیسی: شبیه آلمان ولی مفصل‌تر، عکس لازم، معرف‌ها مهم.',
  tips: ['دقت سوییسی: هیچ غلط املایی و هیچ گپ زمانی قابل‌قبول نیست.', 'زبان‌های آلمانی/فرانسه/ایتالیایی را با مدرک بنویس.', 'معرف‌های قابل‌استعلام بگذار؛ چک می‌شوند.'] },
{ id: 'ct-austria', group: 'country', icon: '🇦🇹', name: 'Österreich', fa: 'اتریش — Lebenslauf', layout: 'tabular', theme: 'crimson', font: 'modern', lang: 'en', photo: 'required', pageMax: 2, pages: '۲ صفحه (جدولی)',
  sections: ['personal', 'exp', 'edu', 'skills', 'langs', 'certs', 'decl'], personal: ['dob', 'pob', 'nat', 'marital'],
  blurb: 'لبنزلاف اتریشی: مثل آلمان — جدولی، عکس‌دار، با امضا.',
  tips: ['قالب و عرف دقیقاً آلمانی است؛ همان قوانین را رعایت کن.', 'برای Red-White-Red Card، سابقه مرتبط را پررنگ کن.', 'مدرک زبان آلمانی (ÖSD/Goethe) را اول بخش زبان‌ها بگذار.'] },
{ id: 'ct-spain', group: 'country', icon: '🇪🇸', name: 'España', fa: 'اسپانیا — CV با عکس', layout: 'card', theme: 'copper', font: 'modern', lang: 'en', photo: 'required', pageMax: 2, pages: 'حداکثر ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs', 'hobbies'], personal: ['dob', 'nat', 'address'],
  blurb: 'رزومه اسپانیایی: عکس‌دار، صمیمی ولی حرفه‌ای، حداکثر ۲ صفحه.',
  tips: ['عکس حرفه‌ای بگذار؛ بدون عکس ناقص به نظر می‌رسد.', 'سطح اسپانیایی را صادانه بنویس (A1 تا C2).', 'برای بخش دولتی شماره NIE لازم می‌شود؛ آماده داشته باش.'] },
{ id: 'ct-italy', group: 'country', icon: '🇮🇹', name: 'Italia', fa: 'ایتالیا — CV با بند حریم خصوصی', layout: 'classic', theme: 'forest', font: 'serif', lang: 'en', photo: 'optional', pageMax: 2, pages: 'حداکثر ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs', 'decl'], personal: ['dob', 'nat', 'address'],
  clause: 'I authorize the processing of my personal data pursuant to Legislative Decree 196/2003 and GDPR (EU) 2016/679.',
  blurb: 'رزومه ایتالیایی: با بند اجازه پردازش داده (حریم خصوصی) در انتها.',
  tips: ['بند GDPR ته رزومه را حتماً نگه دار — در ایتالیا عرف است.', 'عکس رایج ولی اجباری نیست؛ اگر می‌گذاری حرفه‌ای باشد.', 'فرمت Europass هم پذیرفته است ولی این قالب مدرن‌تر دیده می‌شود.'] },
{ id: 'ct-turkey', group: 'country', icon: '🇹🇷', name: 'Türkiye', fa: 'ترکیه — CV با مشخصات کامل', layout: 'card', theme: 'crimson', font: 'modern', lang: 'en', photo: 'required', pageMax: 2, pages: 'حداکثر ۲ صفحه',
  sections: ['summary', 'personal', 'exp', 'edu', 'skills', 'langs'], personal: ['dob', 'pob', 'nat', 'marital', 'gender', 'military'],
  blurb: 'رزومه ترکیه‌ای: عکس‌دار با مشخصات فردی کامل از جمله نظام‌وظیفه.',
  tips: ['تاریخ و محل تولد + وضعیت سربازی را بنویس — استاندارد است.', 'عکس رسمی با کت؛ عکس سلفی = رد شدن.', 'اگر ترکی بلدی سطحش را بنویس؛ خیلی امتیاز دارد.'] },
{ id: 'ct-uae', group: 'country', icon: '🇦🇪', name: 'UAE', fa: 'امارات — CV خلیجی مفصل', layout: 'band', theme: 'gold', font: 'modern', lang: 'en', photo: 'required', pageMax: 3, pages: '۲ تا ۳ صفحه',
  sections: ['objective', 'personal', 'exp', 'edu', 'skills', 'langs', 'refs'], personal: ['dob', 'nat', 'marital', 'visa', 'address'],
  blurb: 'رزومه اماراتی: عکس‌دار، با ملیت و وضعیت ویزا، هدف شغلی در شروع.',
  tips: ['ملیت و وضعیت ویزا (visit/dependent/own visa) را حتماً بنویس.', 'بخش Objective را هدفمند بنویس: «به‌دنبال نقش X در دبی».', 'حقوق درخواستی را در رزومه ننویس؛ در مصاحبه مطرح می‌شود.'] },
{ id: 'ct-nz', group: 'country', icon: '🇳🇿', name: 'New Zealand', fa: 'نیوزیلند — CV مهارت‌محور', layout: 'classic', theme: 'forest', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'refs'], personal: ['visa'],
  blurb: 'رزومه نیوزیلندی: مهارت‌محور، بدون عکس، با حق کار و معرف.',
  tips: ['مهارت‌ها را جلوتر از سوابق بگذار — کیوی‌ها مهارت می‌خرند.', 'وضعیت ویزا/اقامت را شفاف بنویس.', '۲ معرف نیوزیلندی یا بین‌المللی با ایمیل واقعی بگذار.'] },
{ id: 'ct-ireland', group: 'country', icon: '🇮🇪', name: 'Ireland', fa: 'ایرلند — CV دوقلو بریتانیا', layout: 'classic', theme: 'forest', font: 'serif', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۲ صفحه (CV)',
  sections: ['summary', 'exp', 'edu', 'skills', 'certs', 'refs'], personal: [],
  blurb: 'سی‌وی ایرلندی: مثل بریتانیا — ۲ صفحه، بدون عکس و مشخصات شخصی.',
  tips: ['قوانین ضدتبعیض سخت‌گیرانه: عکس و سن ممنوع.', 'برای دابلینِ تک (گوگل/متا/لینکدین) نسخه ATS هم آماده کن.', 'Stamp/وضعیت اقامت را فقط در کاورلتر بگو نه رزومه.'] },
{ id: 'ct-norway', group: 'country', icon: '🇳🇴', name: 'Norway', fa: 'نروژ — CV بدون عکس', layout: 'minimal', theme: 'slate', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs'], personal: [],
  blurb: 'رزومه نروژی: عکس‌ستیزترین کشور اسکاندیناوی — شایستگی خالص.',
  tips: ['عکس نگذار؛ در نروژ حتی از سوئد هم حساس‌ترند.', 'لحن فروتن و دقیق؛ از صفت‌های دهن‌پرکن پرهیز کن.', 'دوره‌ها و گواهینامه‌های نروژی (مثلاً HMS) را برجسته کن.'] },
{ id: 'ct-denmark', group: 'country', icon: '🇩🇰', name: 'Denmark', fa: 'دانمارک — CV با عکس استاندارد', layout: 'card', theme: 'teal', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs', 'hobbies'], personal: ['dob'],
  blurb: 'رزومه دانمارکی: عکس عرف است، لحن صمیمی-حرفه‌ای، تعادل کار/زندگی.',
  tips: ['عکس بگذار — در دانمارک استاندارد است.', 'به فرهنگ hygge و کار تیمی اشاره کن؛ برایشان مهم است.', 'رزومه کوتاه و خوش‌خوان؛ دانمارکی‌ها حاشیه دوست ندارند.'] },
{ id: 'ct-belgium', group: 'country', icon: '🇧🇪', name: 'Belgium', fa: 'بلژیک — CV دوزبانه', layout: 'classic', theme: 'royal', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'edu', 'skills', 'langs', 'certs'], personal: ['dob', 'nat'],
  blurb: 'رزومه بلژیکی: چندزبانه (فرانسه/هلندی امتیاز)، عکس اختیاری.',
  tips: ['هر زبان اضافه (فرانسوی/هلندی/آلمانی) را با سطح بنویس.', 'بسته به منطقه (فلاندر/والونیا) نسخه زبان همان منطقه آماده کن.', 'عکس اختیاری؛ در بروکسل بین‌المللی معمولاً بدون عکس.'] },
{ id: 'ct-singapore', group: 'country', icon: '🇸🇬', name: 'Singapore', fa: 'سنگاپور — CV بدون سن', layout: 'minimal', theme: 'teal', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'certs'], personal: ['nat'],
  blurb: 'رزومه سنگاپوری: بدون عکس و سن (سیاست دولت)، شایستگی‌محور.',
  tips: ['سن، عکس و شماره ID ننویس — دولت سنگاپور منع کرده است.', 'ملیت را می‌توانی بنویسی؛ برای بررسی سهمیه خارجی لازم است.', 'مدرک‌های حرفه‌ای (CPA، PMP، AWS) را برجسته کن.'] },

/* ============ ۱۵ شرکت بین‌المللی ============ */
{ id: 'co-google', group: 'intl', icon: '🔍', name: 'Google', fa: 'گوگل — فرمول X-Y-Z', layout: 'minimal', theme: 'mono', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه (سخت‌گیرانه)',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: [],
  blurb: 'رزومه گوگلی: ۱ صفحه ATS، بولت‌های X-Y-Z (دستاورد با عدد).',
  tips: ['فرمول گوگل: «X کردم (اقدام)، با Y اندازه‌گیری شد، با Z انجام دادم».', 'بیشتر از ۱ صفحه = خوانده نمی‌شود. هر کلمه باید بجنگد.', 'لینک گیت‌هاب و مقالات را در هدر بگذار.'] },
{ id: 'co-microsoft', group: 'intl', icon: '🪟', name: 'Microsoft', fa: 'مایکروسافت — growth mindset', layout: 'classic', theme: 'ocean', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'edu', 'certs', 'projects'], personal: [],
  blurb: 'رزومه مایکروسافتی: تمیز و حرفه‌ای با روحیه رشد و همکاری.',
  tips: ['به growth mindset اشاره کن: یادگیری مداوم و بازخوردپذیری.', 'مدرک‌های Azure/Microsoft را جداگانه و برجسته بنویس.', 'تأثیر روی مشتری و تیم را عددی کن.'] },
{ id: 'co-amazon', group: 'intl', icon: '📦', name: 'Amazon', fa: 'آمازون — رهبری STAR', layout: 'minimal', theme: 'mono', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'skills', 'edu', 'projects'], personal: [],
  blurb: 'رزومه آمازونی: بولت‌های STAR هم‌سو با ۱۶ اصل رهبری.',
  tips: ['بولت‌ها را STAR بنویس و به اصول رهبری (Ownership، Bias for Action) وصل کن.', 'متریک حرف اول را می‌زند: درصد، دلار، زمان تحویل.', 'رزومه را برای Bar Raiser آماده کن: عمق + وسعت.'] },
{ id: 'co-apple', group: 'intl', icon: '🍎', name: 'Apple', fa: 'اپل — مینیمال لوکس', layout: 'band', theme: 'mono', font: 'sharp', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه، وسواسی در جزئیات',
  sections: ['summary', 'exp', 'skills', 'edu', 'projects'], personal: [],
  blurb: 'رزومه اپلی: ۱ صفحه بی‌نقص، تایپوگرافی تمیز، جزئیات وسواسی.',
  tips: ['یک غلط املایی = خداحافظی. سه بار پرینت بگیر و بخوان.', 'به craft و جزئیات محصول اشاره کن، نه فقط تکنولوژی.', 'کمتر = بهتر؛ فقط قوی‌ترین ۴-۵ دستاورد.'] },
{ id: 'co-meta', group: 'intl', icon: '♾️', name: 'Meta', fa: 'متا — ایمپکت متریک', layout: 'minimal', theme: 'mono', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: [],
  blurb: 'رزومه متا: ایمپکت‌محور با متریک‌های مقیاس (میلیون کاربر).',
  tips: ['مقیاس را نشان بده: کاربر، ترافیک، درآمد تحت‌تأثیر.', 'سرعت حرکت (move fast) را با تحویل‌های سریع اثبات کن.', 'برای نقش‌های AI، پروژه‌ها را جلوتر بیاور.'] },
{ id: 'co-nvidia', group: 'intl', icon: '💚', name: 'NVIDIA', fa: 'انویدیا — مهندسی عمیق', layout: 'classic', theme: 'forest', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu', 'certs'], personal: [],
  blurb: 'رزومه انویدیا: عمق مهندسی (GPU/AI/سیستم) + پروژه‌های فنی.',
  tips: ['استک فنی دقیق: CUDA، TensorRT، PyTorch با سطح تسلط.', 'بهینه‌سازی و بنچمارک عددی (x برابر سریع‌تر) طلایی است.', 'مقاله و پتنت را در پروژه‌ها/تحصیلات بیاور.'] },
{ id: 'co-netflix', group: 'intl', icon: '🎬', name: 'Netflix', fa: 'نتفلیکس — آزادی و مسئولیت', layout: 'band', theme: 'crimson', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه، رک و شفاف',
  sections: ['summary', 'exp', 'skills', 'projects', 'edu'], personal: [],
  blurb: 'رزومه نتفلیکسی: مختصر، رک، با اثبات قضاوت مستقل.',
  tips: ['فرهنگ نتفلیکس: آزادی و مسئولیت — تصمیم‌های مستقلت را نشان بده.', 'چگالی استعداد: فقط دستاوردهای درجه‌یک، بدون پرکننده.', 'شفافیت رادیکال: حتی از شکست‌های آموزنده بگو.'] },
{ id: 'co-tesla', group: 'intl', icon: '⚡', name: 'Tesla', fa: 'تسلا — first principles', layout: 'minimal', theme: 'mono', font: 'sharp', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه فشرده',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: [],
  blurb: 'رزومه تسلا: فشرده و فنی، حل مسئله از اصول اول.',
  tips: ['مدرک مهم نیست، خروجی مهم است: چه ساختی؟ چه بهینه کردی؟', 'سرعت و شدت کار را با تحویل‌های واقعی نشان بده.', 'پروژه‌های سخت‌افزاری/رباتیک را با عکس لینک‌دار بیاور.'] },
{ id: 'co-openai', group: 'intl', icon: '🧠', name: 'OpenAI', fa: 'اوپن‌ای‌آی — مأموریت‌محور', layout: 'minimal', theme: 'mono', font: 'modern', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه',
  sections: ['summary', 'projects', 'exp', 'skills', 'edu'], personal: [],
  blurb: 'رزومه اوپن‌ای‌آی: پروژه‌های AI جلوتر از همه + مأموریت.',
  tips: ['پروژه‌های ML/AI را اول بیاور: مدل، دیتاست، نتیجه.', 'به AGI safety و مأموریت اشاره کوتاه و صادانه کن.', 'انتشار، اوپن‌سورس و بنچمارک‌ها را لینک بده.'] },
{ id: 'co-mckinsey', group: 'intl', icon: '💼', name: 'McKinsey', fa: 'مک‌کنزی — تحصیلات اول', layout: 'classic', theme: 'navy', font: 'serif', lang: 'en', photo: 'forbidden', pageMax: 1, pages: 'دقیقاً ۱ صفحه',
  sections: ['edu', 'exp', 'skills', 'langs', 'hobbies'], personal: [],
  blurb: 'رزومه مشاوره‌ای: تحصیلات اول (با معدل)، ایمپکت عددی، علایق خاص.',
  tips: ['تحصیلات اول با GPA/رتبه — مک‌کنزی عاشق سیگنال آکادمیک است.', 'هر بولت: اقدام + نتیجه عددی + مهارت (تحلیل/رهبری).', 'علایق خاص و متمایز بنویس (نه «سفر و موسیقی»).'] },
{ id: 'co-goldman', group: 'intl', icon: '🏦', name: 'Goldman Sachs', fa: 'گلدمن ساکس — وال‌استریت', layout: 'classic', theme: 'charcoal', font: 'serif', lang: 'en', photo: 'forbidden', pageMax: 1, pages: 'دقیقاً ۱ صفحه',
  sections: ['edu', 'exp', 'skills', 'certs', 'hobbies'], personal: [],
  blurb: 'رزومه وال‌استریت: ۱ صفحه، دیل‌ها و اعداد، خط علایق ته صفحه.',
  tips: ['مقادیر دیل (M&A، $Xm) را دقیق و راستی‌آزمایی‌پذیر بنویس.', 'مدل‌سازی و ابزار مالی (Excel، Bloomberg) را مشخص کن.', 'خط Interests ته صفحه در وال‌استریت رسم است — خاص بنویس.'] },
{ id: 'co-samsung', group: 'intl', icon: '📱', name: 'Samsung', fa: 'سامسونگ — گلوبال شرقی', layout: 'card', theme: 'slate', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'exp', 'skills', 'edu', 'langs', 'certs'], personal: [],
  blurb: 'رزومه سامسونگی: انگلیسی تمیز، احترام به سلسله‌مراتب، نتیجه‌محور.',
  tips: ['انگلیسی رسمی و مؤدب؛ از اغراق فردی پرهیز کن.', 'تجربه کار تیمی چندملیتی را برجسته کن.', 'برای دفتر کره، انعطاف فرهنگی را نشان بده.'] },
{ id: 'co-siemens', group: 'intl', icon: '🏭', name: 'Siemens', fa: 'زیمنس — صنعتی دقیق', layout: 'tabular', theme: 'teal', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۲ صفحه',
  sections: ['personal', 'exp', 'edu', 'skills', 'certs', 'langs'], personal: ['dob', 'nat'],
  blurb: 'رزومه زیمنس: شبه‌آلمانی دقیق با مدارک فنی و زبان‌ها.',
  tips: ['مدارک فنی (PLC، اتوماسیون، PMP) را کامل بیاور.', 'پروژه‌های صنعتی را با مقیاس (MW، خط تولید) بنویس.', 'آلمانی حتی پایه، امتیاز مثبت دارد.'] },
{ id: 'co-sap', group: 'intl', icon: '🧩', name: 'SAP', fa: 'اس‌ای‌پی — ماژول و مدرک', layout: 'classic', theme: 'ocean', font: 'modern', lang: 'en', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه',
  sections: ['summary', 'skills', 'exp', 'certs', 'edu', 'langs'], personal: [],
  blurb: 'رزومه SAP: ماژول‌ها و مدرک‌های SAP قلب رزومه‌اند.',
  tips: ['ماژول‌ها (MM/SD/FI/HANA) را در مهارت‌ها اول بیاور.', 'مدرک‌های SAP Certified را با کد و سال بنویس.', 'پروژه‌های پیاده‌سازی را با نقش و اندازه بنویس.'] },
{ id: 'co-spotify', group: 'intl', icon: '🎧', name: 'Spotify', fa: 'اسپاتیفای — اسکواد مدرن', layout: 'band', theme: 'forest', font: 'round', lang: 'en', photo: 'forbidden', pageMax: 1, pages: '۱ صفحه',
  sections: ['summary', 'exp', 'skills', 'projects', 'edu', 'hobbies'], personal: [],
  blurb: 'رزومه اسپاتیفای: مدرن و صمیمی ولی ATS-امن، فرهنگ اسکوادی.',
  tips: ['به همکاری چابک (squad/chapter) اشاره کن.', 'پروژه‌های شخصی و اوپن‌سورس را جدی بگیر.', 'علایق موسیقی/خلاقیت را واقعی و خاص بنویس.'] },

/* ============ ۱۵ شرکت ایرانی ============ */
{ id: 'ir-digikala', group: 'iran', icon: '🛒', name: 'Digikala', fa: 'دیجی‌کالا — مقیاس بزرگ', layout: 'sidebar', theme: 'crimson', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'skills', 'exp', 'edu', 'projects', 'langs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه دیجی‌کالایی: فارسی تمیز، مقیاس و عدد، مهارت‌های به‌روز.',
  tips: ['مقیاس را نشان بده: ترافیک، سفارش، کاربر تحت‌تأثیر.', 'برای تک: استک دقیق + لینک گیت‌هاب؛ برای غیرتک: KPI عددی.', 'دیجی‌کالا فرهنگ بازخورد دارد — از رشدت بگو.'] },
{ id: 'ir-snapp', group: 'iran', icon: '🚕', name: 'Snapp', fa: 'اسنپ — سرعت و رشد', layout: 'band', theme: 'forest', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'edu', 'langs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه اسنپی: رشد سریع، عملیات، عدد و سرعت اجرا.',
  tips: ['سرعت اجرا و رشد را اثبات کن: «در ۳ ماه X را Y کردم».', 'تجربه محیط شلوغ و پرفشار (ops) امتیاز است.', 'رزومه را کوتاه و پرانرژی نگه دار.'] },
{ id: 'ir-cafebazaar', group: 'iran', icon: '☕', name: 'Cafe Bazaar', fa: 'کافه‌بازار — محصول‌محور', layout: 'classic', theme: 'teal', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'projects', 'edu', 'langs'], personal: ['dob', 'military'],
  blurb: 'رزومه کافه‌بازاری: محصول و کاربر در مرکز، اندروید پلاس.',
  tips: ['به محصول و کاربر وصل شو: «فیچر X، ریزش را Y٪ کم کرد».', 'برای اندروید/بک‌اند: لینک اپ و گیت‌هاب بگذار.', 'کافه‌بازار قدیمی‌ترین استارتاپ‌هاست — بلوغ حرفه‌ای نشان بده.'] },
{ id: 'ir-divar', group: 'iran', icon: '📢', name: 'Divar', fa: 'دیوار — مهندسی تمیز', layout: 'minimal', theme: 'charcoal', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: ['dob', 'military'],
  blurb: 'رزومه دیواری: مهندسی تمیز، بدون حاشیه، عمق فنی.',
  tips: ['دیوار عاشق مهندسی خوب است: معماری، تست، کیفیت کد.', 'مقیاس (رکورد، ریکوئست) را عددی کن.', 'رزومه فارسی ولی اصطلاحات فنی انگلیسی دقیق.'] },
{ id: 'ir-tapsi', group: 'iran', icon: '🛵', name: 'Tapsi', fa: 'تپسی — چابک و جسور', layout: 'band', theme: 'copper', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'edu', 'langs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه تپسی: چابکی، مالکیت، رشد در رقابت.',
  tips: ['مالکیت (ownership) را با مثال اثبات کن.', 'در بازار رقابتی چه مزیتی ساختی؟ عدد بده.', 'انرژی و سرعت یادگیری را نشان بده.'] },
{ id: 'ir-alibaba', group: 'iran', icon: '✈️', name: 'Alibaba.ir', fa: 'علی‌بابا — سفر و مقیاس', layout: 'classic', theme: 'ocean', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'edu', 'langs', 'certs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه علی‌بابا: سفر، مشتری‌محوری، عملیات دقیق.',
  tips: ['مشتری‌محوری و دقت عملیاتی را برجسته کن.', 'انگلیسی قوی برای این صنعت حیاتی است — مدرکش را بیاور.', 'آمار فروش/رشد/رضایت را عددی کن.'] },
{ id: 'ir-snappfood', group: 'iran', icon: '🍔', name: 'SnappFood', fa: 'اسنپ‌فود — عملیات پرحجم', layout: 'band', theme: 'wine', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'edu', 'langs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه اسنپ‌فود: عملیات پرحجم، مارکتینگ عددی، سرعت.',
  tips: ['حجم عملیات (سفارش روزانه، شهرها) را بنویس.', 'برای مارکتینگ: CAC، ریزش، کمپین با عدد.', 'آمادگی شیفت فشرده را تلویحی نشان بده.'] },
{ id: 'ir-torob', group: 'iran', icon: '🔎', name: 'Torob', fa: 'ترب — دیتا و سادگی', layout: 'minimal', theme: 'teal', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: ['dob', 'military'],
  blurb: 'رزومه ترب: دیتامحور، ساده و دقیق، بدون شلوغی.',
  tips: ['دیتا حرف اول: کوئری، داشبورد، A/B تست با نتیجه.', 'سادگی و دقت؛ رزومه شلوغ با فرهنگ ترب نمی‌خواند.', 'پروژه‌های شخصی دیتایی را لینک بده.'] },
{ id: 'ir-filimo', group: 'iran', icon: '🎞️', name: 'Filimo', fa: 'فیلیمو — رسانه و خلاقیت', layout: 'sidebar', theme: 'wine', font: 'round', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'projects', 'skills', 'edu', 'langs'], personal: ['dob'],
  blurb: 'رزومه فیلیمو: رسانه‌ای، نمونه‌کار مهم‌تر از مدرک.',
  tips: ['لینک نمونه‌کار (ویدیو، کمپین، محتوا) حیاتی است.', 'آمار بازدید/فالوور/نرخ تعامل را بنویس.', 'خلاقیت را در خود رزومه هم نشان بده (ولی خوانا).'] },
{ id: 'ir-aparat', group: 'iran', icon: '📺', name: 'Aparat', fa: 'آپارات — ویدیو و تکنولوژی', layout: 'sidebar', theme: 'slate', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'skills', 'exp', 'projects', 'edu'], personal: ['dob', 'military'],
  blurb: 'رزومه آپارات: ویدیو-تک، مقیاس پخش، مهندسی و محصول.',
  tips: ['تجربه ویدیو/استریم/CDN را برجسته کن.', 'مقیاس (بازدید همزمان، پهنای باند) را عددی کن.', 'لینک کانال/پروژه‌های ویدیویی بگذار.'] },
{ id: 'ir-irancell', group: 'iran', icon: '📡', name: 'Irancell', fa: 'ایرانسل — تلکام رسمی', layout: 'classic', theme: 'gold', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'personal', 'exp', 'edu', 'skills', 'certs', 'langs'], personal: ['dob', 'marital', 'military', 'address', 'nat'],
  blurb: 'رزومه ایرانسل: رسمی-شرکتی، مشخصات کامل، مدارک.',
  tips: ['ساختار رسمی: مشخصات، سوابق، تحصیلات، مدارک.', 'مدرک‌های مخابراتی/مدیریتی (PMP، ITIL) را کامل بیاور.', 'انگلیسی را با مدرک (آیلتس/تافل) اثبات کن.'] },
{ id: 'ir-mapna', group: 'iran', icon: '🏗️', name: 'MAPNA', fa: 'مپنا — صنعتی سنگین', layout: 'tabular', theme: 'charcoal', font: 'serif', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۲ صفحه (فارسی)',
  sections: ['personal', 'exp', 'edu', 'skills', 'certs', 'langs'], personal: ['dob', 'marital', 'military', 'address'],
  blurb: 'رزومه مپنا: صنعتی، جدولی، پروژه‌های نیروگاهی/نفتی.',
  tips: ['پروژه‌ها را با ظرفیت (MW) و نقش دقیق بنویس.', 'ایمنی (HSE) و استانداردها را برجسته کن.', 'آمادگی مأموریت شهرستانی را ذکر کن.'] },
{ id: 'ir-pasargad', group: 'iran', icon: '🏛️', name: 'Bank Pasargad', fa: 'بانک پاسارگاد — بانکی رسمی', layout: 'classic', theme: 'forest', font: 'serif', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'personal', 'edu', 'exp', 'skills', 'certs'], personal: ['dob', 'marital', 'military', 'address', 'nat'],
  blurb: 'رزومه بانکی: بسیار رسمی، تحصیلات جلوتر، بدون خلاقیت بصری.',
  tips: ['بانک = رسمیت مطلق: فونت ساده، بدون رنگ جیغ.', 'تحصیلات (معدل، دانشگاه) را جلوتر بیاور.', 'امانت‌داری و دقت را با سابقه اثبات کن.'] },
{ id: 'ir-hamkaran', group: 'iran', icon: '💻', name: 'Hamkaran System', fa: 'همکاران سیستم — ERP', layout: 'classic', theme: 'navy', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'skills', 'exp', 'certs', 'edu', 'langs'], personal: ['dob', 'marital', 'military'],
  blurb: 'رزومه همکاران‌سیستم: راهکاران، سپیدار، پیاده‌سازی ERP.',
  tips: ['ماژول‌های سپیدار/راهکاران مسلط را لیست کن.', 'پروژه‌های استقرار را با صنعت مشتری بنویس.', 'مدرک‌های حسابداری/نرم‌افزار را کامل بیاور.'] },
{ id: 'ir-sabaidea', group: 'iran', icon: '💡', name: 'SabaIdea', fa: 'صباایده — هولدینگ دیجیتال', layout: 'sidebar', theme: 'royal', font: 'modern', lang: 'fa', photo: 'optional', pageMax: 2, pages: '۱ تا ۲ صفحه (فارسی)',
  sections: ['summary', 'exp', 'skills', 'projects', 'edu', 'langs'], personal: ['dob', 'military'],
  blurb: 'رزومه صباایده: دیجیتال چندکسب‌وکاری (آپارات/فیلیمو/میهن).',
  tips: ['چندمهارتی بودن را نشان بده: محصول، محتوا، تک.', 'آشنایی با کسب‌وکارهای گروه امتیاز است.', 'نمونه‌کار دیجیتال لینک بده.'] },
];

export const GROUPS = {
  country: { title: '🌍 سفارت و کارفرمای خارجی (۲۰ کشور)', desc: 'قالب دقیق هر کشور با عرف واقعی عکس، مشخصات و طول صفحه' },
  intl: { title: '🚀 شرکت‌های بین‌المللی (۱۵ شرکت)', desc: 'فرهنگ استخدامی هر شرکت در ساختار رزومه لحاظ شده' },
  iran: { title: '🏢 شرکت‌های ایرانی (۱۵ شرکت)', desc: 'فارسی، راست‌چین، با نظام‌وظیفه و عرف جذب ایران' },
};

export function getTemplate(id, customTpls = []) {
  return TEMPLATES.find((t) => t.id === id) || (customTpls || []).find((t) => t.id === id) || null;
}
